name: Deploy to Cloud Run

on:
  push:
    branches: [main]  # PR merges to main trigger CD
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.TF_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Verify Authentication
      run: gcloud auth list

    - name: Verify Project Access
      run: gcloud config list

    - name: List Cloud Run Services
      run: |
        gcloud run services list \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }}

    # - name: Authenticate Docker to GCR
    #   run: |
    #     gcloud auth configure-docker

    # - name: Build and Push Docker image
    #   run: |
    #     IMAGE="gcr.io/${{ secrets.GCP_PROJECT }}/my-app:${{ github.sha }}"
    #     docker build -t $IMAGE .
    #     docker push $IMAGE

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy my-app \
    #       --image=gcr.io/${{ secrets.GCP_PROJECT }}/my-app:${{ github.sha }} \
    #       --region=${{ secrets.GCP_REGION }} \
    #       --platform=managed \
    #       --allow-unauthenticated \
    #       --service-account=github-cd@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
